CREATE TABLE IF NOT EXISTS `games` (
  `id` int NOT NULL AUTO_INCREMENT,
  `sport` varchar(100) DEFAULT NULL,
  `date` date DEFAULT NULL,
  `homeTeam` varchar(100) DEFAULT NULL,
  `awayTeam` varchar(100) DEFAULT NULL,
  `homeMoneyLineOdds` int DEFAULT NULL,
  `awayMoneyLineOdds` int DEFAULT NULL,
  `homeSpread` varchar(100) NULL,
  `homeSpreadOdds` int DEFAULT NULL,
  `awaySpread` varchar(100) DEFAULT NULL,
  `awaySpreadOdds` int DEFAULT NULL,
  `over` int DEFAULT NULL,
  `overOdds` int DEFAULT NULL,
  `under` int DEFAULT NULL,
  `underOdds` int DEFAULT NULL,
  `drawOdds` int DEFAULT NULL,
  `homeMoneyLineResult` varchar(100) DEFAULT NULL,
  `awayMoneyLineResult` varchar(100) DEFAULT NULL,
  `homeSpreadResult` varchar(100) DEFAULT NULL,
  `awaySpreadResult` varchar(100) DEFAULT NULL,
  `overResult` varchar(100) DEFAULT NULL,
  `underResult` varchar(100) DEFAULT NULL,
  `drawResult` varchar(100) DEFAULT NULL,
  PRIMARY KEY (ID))